### ISSUE TITLE
Socket server example gives runtime error when more than one client connects

### ISSUE THREAD

**Issue by hkutluca** [tglane/socketwrapper#1]
Hello changed your code so that one receiver stays live to accept calls and sender periodically sends data. Single sender, single receiver it works fine but when i run second sender the code gives runtime error and exits. Maybe I need to add some more code to example to make it working?

#include "../socketwrapper.hpp"
#include <iostream>
#include <thread>
#include <cstring>

int main(int argc, char**argv)
{
    if(argc <= 1)
        return 0;

    if(strcmp(argv[1], "r") == 0)
    {
        std::cout << "--- Receiver ---\n";
     /*   net::tcp_acceptor<net::ip_version::v4> acceptor_two {"0.0.0.0", 4556};
        acceptor_two.async_accept([](net::tcp_connection<net::ip_version::v4>&& sock) {
            std::cout << sock.get() << std::endl;
        });
*/
        net::tcp_acceptor<net::ip_version::v4> acceptor {"0.0.0.0", 5060};
        std::cout << "Waiting for accept\n";
        std::vector<net::tcp_connection<net::ip_version::v4>> conns;
        acceptor.async_accept([&conns](net::tcp_connection<net::ip_version::v4>&& conn) {
            std::array<char, 1024> buffer;
            std::cout << "Accepted\n";

            conns.push_back(std::move(conn));
            auto& sock = conns.back();
            sock.async_read(net::span {buffer}, [&buffer](size_t br){
                std::cout << "Received: " << br << " - " << std::string_view {buffer.data(), br} << '\n';
            });
        });

        std::cout << "Wait for data ...\n";
        std::this_thread::sleep_for(std::chrono::milliseconds(100000));
    }
    else if(strcmp(argv[1], "s") == 0)
    {
        {
            std::cout << "--- Sender ---\n";
            net::tcp_connection<net::ip_version::v4> sock {"127.0.0.1", 5060};
            std::cout << "Connected\n";
            std::vector<char> vec {'H', 'e', 'l', 'l', 'o'};

            std::this_thread::sleep_for(std::chrono::milliseconds(2000));
            std::string_view buffer {"Hello String_view-World"};
            sock.send(net::span {buffer.begin(), buffer.end()});

            std::cout << "Sent\n";
        }
        {
            std::cout << "--- Sender ---\n";
            net::tcp_connection<net::ip_version::v4> sock {"127.0.0.1", 5060};
            std::cout << "Connected\n";
            std::vector<char> vec {'H', 'e', 'l', 'l', 'o'};
            // sock.send(net::span {vec});
            // sock.send(net::span {std::string {"Hello World"}});
while(true){
            std::this_thread::sleep_for(std::chrono::milliseconds(500));
            std::string_view buffer {"Hello String_view     -World"};
            sock.send(net::span {buffer.begin(), buffer.end()});
}
            std::cout << "Sent\n";
        }
    }
}

**Comment by tglane** [comment]
Hey @hkutluca sorry that i completely missed your issue. I worked on the async implementation until a few days ago. Is it possible to check if your bug occurs with the newest version of the lib?

**Comment by tglane** [comment]
@hkutluca Now I see the problem with your code. The async operations work like they do in boost asio. So when you call async_accept the socket will execute the callback function only once. So to have a socket that is able to accept multiple connections you have to call async_accept in your callback again. Same goes for async read/write actions.

I need to add this to the readme file to make this clear right away. And maybe i need to add some functionality to register a callback for more than one use, but currently the system works like described above.

**Comment by tglane** [comment]
Ok i dug deeper into this and it seems that my async tcp example was not clear enough. When you dynamically add connections to the vector of tcp_connections you have to make sure that the sockets are not moved because of vector resizing. Because than the callback gets called on a "moved-from" socket wich stores an invalid file descriptor (the socket holding the file descriptor was moved to a different location when resizing the vector). I hope this makes sense :D 

Here is a little example that should show what you want

```cpp
#include "../socketwrapper.hpp"

#include <cstring>
#include <vector>
#include <array>
#include <string>
#include <string_view>
#include <iostream>

using tcp_connection_v4 = net::tcp_connection<net::ip_version::v4>;
using tcp_acceptor_v4 = net::tcp_acceptor<net::ip_version::v4>;

void sender()
{
    int i = 0;
    while(i++ <= 6)
    {
        tcp_connection_v4 sock {"127.0.0.1", 5566};

        std::string str {"Hello world kek"};
        str.append(std::to_string(i));
        sock.send(net::span {str});
        std::cout << "Sent...\n";
    }
}

void receiver()
{
    tcp_acceptor_v4 a {"0.0.0.0", 5566};

    // Make sure to prevent calling the callback on a moved-from (invalid) socket if you use references to async sockets
    std::vector<tcp_connection_v4> store;
    store.reserve(128);

    std::function<void(tcp_connection_v4&&)> acceptor;
    acceptor = [&acceptor, &a, &store](tcp_connection_v4&& conn) {
        std::cout << "Accepted!\n";
        a.async_accept(acceptor);

        store.push_back(std::move(conn));
        auto& conn_ref = store.back();
        std::array<char, 1024> buffer;
        conn_ref.async_read(net::span {buffer}, [&buffer](size_t br) {
            std::cout << "Received " << br << " bytes: " << std::string_view {buffer.data(), br} << '\n';
        });
    };

    a.async_accept(acceptor);
    std::cout << "Waiting for incoming connections...\n";

    net::async_run();
}

int main(int argc, char**argv)
{
    if(argc <= 1)
        return 0;

    if(strcmp(argv[1], "r") == 0)
        receiver();
    else if(strcmp(argv[1], "s") == 0)
        sender();
}

```

**Comment by hkutluca** [comment]
Great. Thanks for detailed explanation. Thıs solves my problem
