### ISSUE TITLE
getting a warning about a it saying something in async is deprecated

### ISSUE THREAD

**Issue by tanja84dk** [tglane/socketwrapper#22]
Just a little heads up I'm getting this warning in Visual Studio Code on Ubuntu 20.04 compiling with GCC 11
And I'm using Cmake to include the header only library as a INTERFACE

I have tried to clone a brand new up to date version of your repo and it still gives me the warning

Btw I do store all external libraries in the project folder in Libraries/External for easier management and that is why the path is starting with that

```
[build] Libraries/External/Cpp-socketwrapper/include/socketwrapper/detail/async.hpp: In member function ‘bool net::detail::async_context::add(int, net::detail::async_context::event_type, CALLBACK_TYPE&&)’:
[build] Libraries/External/Cpp-socketwrapper/include/socketwrapper/detail/async.hpp:125:38: warning: bitwise operation between different enumeration types ‘const net::detail::async_context::event_type’ and ‘EPOLL_EVENTS’ is deprecated [-Wdeprecated-enum-enum-conversion]
[build]   125 |             item.event.events = type | EPOLLET;
[build]       |                                      ^
```

And noticed you had made a issue about a month ago about async so were starting to think it were related wich is why I wanted to inform you

**Comment by tglane** [comment]
Hey thank you for the information! I really appreciate this. I think i "fixed" it in 731f35da9e2903d4f72336058a0e73125a113608. I would like to get some feedback from you :)

Maybe i need to build my examples and tests with more warnings enabled :D

**Comment by tanja84dk** [comment]
Fist of all thank you very much for getting back so quickly.

I have done some digging including isolating your library for it self and also tried to compile your examples.

What I have found out out is that it looks like its something around the error I showed there is deprecated in C++20 ( so still valid but is on the way out ) because when I lower my version to C++17 the warning goes away and no errors or warnings

And at this point it were actually just a clean project with a clean main function because I were trying to get the needed libraries to work first before starting to code the project ( to not have to redo a lot if I had ti change some libraries )

so it were from including the header alone that I noticed it

So im sorry I took your time

**Comment by tglane** [comment]
Just to clarify: Did you test the latest commit from branch [fix](https://github.com/tglane/socketwrapper/tree/fix/prevent-deprecated-enum-conversion)? I think it should solve youre problem even with c++20 mode enabled.

**Comment by tanja84dk** [comment]
Thank you very much for getting me to double check and I'm sorry actually I thought were but noticed now where I checked the git files it had pulled the master and not the branch you asked me to test

I have just tried including that and both setting cmake to c++17 and c++20 both with -Wall -Werror -Wextra, and no warnings nether on the example files nor the header library itself when trying to run the compiling.

And I'm sorry for my mistake thinking I had tested [fix](https://github.com/tglane/socketwrapper/tree/fix/prevent-deprecated-enum-conversion) where it actually were master my system pulled again

So thank you very much for all your work and quick replies and getting me to double check

**Comment by tglane** [comment]
Haha absolutely no problem :) 
I'm happy if someone uses this stuff im working on. Im also thankful for every issue created here because this means i can improve the library and learn some stuff about C++.

So thank you, too :) I will merge the fix from [fix branch](https://github.com/tglane/socketwrapper/tree/fix/prevent-deprecated-enum-conversion) into the master branch.
