### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by novitae** [tglane/socketwrapper#33]
Hey, where could I contact you in private about your project and some related stuff ?

**Comment by tglane** [comment]
What would you like to talk about? You are welcome to ask any project related questions here in this issue.

**Comment by novitae** [comment]
Id like to talk to you about a mission related to TLS, C++ and python, but id rather elaborate in private if you don't mind.

**Comment by tglane** [comment]
Ok, I'll contact you via Discord. Is the username on your GH profile correct?

**Comment by novitae** [comment]
Nope, I don't have it anymore ... You can contact me on twitter, my dms are open to everyone. Thanks !
